# this is the name of the workflow, which can hold multiple steps
name: "Sphinx: Render docs"
# run whenever I push to the repo
on: push

# created from 
# https://www.sphinx-doc.org/en/master/tutorial/deploying.html#id5
# https://docs.astral.sh/uv/guides/integration/github/#using-uv-in-github-actions

jobs:
  # huh, it's all happening under the "build" job?
  build:
    # specify the Docker image to run on
    runs-on: ubuntu-latest
    # write to what?
    permissions:
      contents: write
    # specify the steps to use as a list
    steps:
    # check out my repo
    - name: Check Out Repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    # install Python version specified in the UV .python-version file
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    # install UV (best practice to specify a particular version)
    - name: Install UV
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.2"
    # create requirements.txt from UV for pip to use
    - name: Create requirements.txt
      run: uv export --group docs > requirements.txt
    # pip install the requirements.txt since each 'run' occurs in its own shell and they're not using the UV .venv
    - name: Pip install Requirements
      run: pip install -r requirements.txt
    # use UV to install Python dependencies
    #- name: Install Python Dependencies with UV
      #run: uv sync --locked --all-groups
      # try installing packages to the system environment so later commands will use them
    #  run: uv pip install --system
    # add UV-installed dependencies to default PATH (each "run" occurs in its own shell), otherwise I'd just do 'source .venv/bin/activate'
    #- name: Activate UV virtual environment
      # tried the following to get the later commands to use the .venv, without success
      #run: echo PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH >> $GITHUB_ENV
      #run: |
      #  source .venv/bin/activate
      #  echo PATH=$PATH >> $GITHUB_ENV
    # build the HTML documentation
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    # upload the HTML artifacts for the Deploy step to use
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    # deploy HTML artifacts to GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html