# this is the name of the workflow, which can hold multiple steps
name: "Sphinx: Render docs"
# run whenever I push to the repo
on: push

# created from 
# https://www.sphinx-doc.org/en/master/tutorial/deploying.html#id5
# https://docs.astral.sh/uv/guides/integration/github/#using-uv-in-github-actions

jobs:
  # huh, it's all happening under the "build" job?
  build:
    # specify the Docker image to run on
    runs-on: ubuntu-latest
    # write to what?
    permissions:
      contents: write
    # specify the steps to use as a list
    steps:
    # check out my repo
    - name: Check Out Repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    # install UV (best practice to specify a particular version)
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.2"
    # use UV to install Python dependencies
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    # build the HTML documentation
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    # upload the html artifacts for the Deploy step to use
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    # deploy html artifacts to GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html